// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace RebacExperiments.Shared.ApiSdk.Models {
    public enum TaskItemPriorityEnum {
        [EnumMember(Value = "Low")]
        Low,
        [EnumMember(Value = "Normal")]
        Normal,
        [EnumMember(Value = "High")]
        High,
    }
}
