// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace RebacExperiments.Shared.ApiSdk.Models {
    public enum UserTaskStatusEnum {
        [EnumMember(Value = "NotStarted")]
        NotStarted,
        [EnumMember(Value = "InProgress")]
        InProgress,
        [EnumMember(Value = "Completed")]
        Completed,
        [EnumMember(Value = "Deferred")]
        Deferred,
    }
}
