CREATE TABLE [Application].[TaskItem](
    [TaskItemID]            INT                                         CONSTRAINT [DF_Application_TaskItem_TaskItemID] DEFAULT (NEXT VALUE FOR [Application].[sq_TaskItem]) NOT NULL,
    [Title]                 NVARCHAR(50)                                NOT NULL,
    [Description]           NVARCHAR(2000)                              NOT NULL,
    [DueDateTime]           DATETIME2(7)                                NULL,
    [ReminderDateTime]      DATETIME2(7)                                NULL,
    [CompletedDateTime]     DATETIME2(7)                                NULL,
    [AssignedTo]            INT                                         NULL,
    [TaskItemPriorityID]    INT                                         NOT NULL,
    [TaskItemStatusID]      INT                                         NOT NULL,
    [RowVersion]            ROWVERSION                                  NULL,
    [LastEditedBy]          INT                                         NOT NULL,
    [ValidFrom]             DATETIME2 (7) GENERATED ALWAYS AS ROW START NOT NULL,
    [ValidTo]               DATETIME2 (7) GENERATED ALWAYS AS ROW END   NOT NULL,
    CONSTRAINT [PK_TaskItem] PRIMARY KEY ([TaskItemID]),
    CONSTRAINT [FK_TaskItem_TaskItemPriority_TaskItemPriorityID] FOREIGN KEY ([TaskItemPriorityID]) REFERENCES [Application].[TaskItemPriority] ([TaskItemPriorityID]),
    CONSTRAINT [FK_TaskItem_TaskItemStatus_TaskItemStatusID] FOREIGN KEY ([TaskItemStatusID]) REFERENCES [Application].[TaskItemStatus] ([TaskItemStatusID]),
    CONSTRAINT [FK_TaskItem_User_LastEditedBy] FOREIGN KEY ([LastEditedBy]) REFERENCES [Identity].[User] ([UserID]),
    CONSTRAINT [FK_TaskItem_User_AssignedTo] FOREIGN KEY ([AssignedTo]) REFERENCES [Identity].[User] ([UserID]),
    PERIOD FOR SYSTEM_TIME (ValidFrom, ValidTo)
) WITH (SYSTEM_VERSIONING = ON (HISTORY_TABLE = [Application].[TaskItemHistory]));