@RebacExperiments.Server.Api_HostAddress = https://localhost:5000/odata

### Sign In "philipp@bytefish.de"

POST {{RebacExperiments.Server.Api_HostAddress}}/SignInUser
Content-Type: application/json

{
  "username": "philipp@bytefish.de",
  "password": "5!F25GbKwU3P",
  "rememberMe": true
}

### Read all Relationships

GET {{RebacExperiments.Server.Api_HostAddress}}/RelationTuples

### Create a new Relation 

POST {{RebacExperiments.Server.Api_HostAddress}}/RelationTuples
Content-Type: application/json

{
    "id": "131312",
    "store": "34242342",
    "object": "TaskItem",
    "relation": "",
    "subject": "User:2",
}


### Get RelationTuples

POST {{RebacExperiments.Server.Api_HostAddress}}/GetRelationTuples
Content-Type: application/json

{
  "tuple": {
      "object": "TaskItem:152",  
      "relation": "owner",
      "subject": "User:"
  }
}


### Delete TaskItem

DELETE {{RebacExperiments.Server.Api_HostAddress}}/TaskItems(38197)


### Get all TaskItems for "philipp@bytefish.de"

GET {{RebacExperiments.Server.Api_HostAddress}}/TaskItems

### Get the first task and return the total count of Entities visible to "philipp@bytefish.de"

GET {{RebacExperiments.Server.Api_HostAddress}}/TaskItems?$top=1&$orderby=id&$count=true

### Sign Out "philipp@bytefish.de"

POST {{RebacExperiments.Server.Api_HostAddress}}/SignOutUser

### Sign In as "max@mustermann.local"

POST {{RebacExperiments.Server.Api_HostAddress}}/SignInUser
Content-Type: application/json

{
  "username": "max@mustermann.local",
  "password": "5!F25GbKwU3P",
  "rememberMe": true
}

### Get all TaskItems for "max@mustermann.local"

GET {{RebacExperiments.Server.Api_HostAddress}}/TaskItems

### Create a new TaskItem "API HTTP File Example" as "max@mustermann.local"

POST {{RebacExperiments.Server.Api_HostAddress}}/TaskItems
Content-Type: application/json

{
    "title": "API HTTP File Example",
    "description": "API HTTP File Example",
    "dueDateTime": null,
    "reminderDateTime": null,
    "completedDateTime": null,
    "assignedTo": null,
    "TaskItemPriority": "Normal",
    "TaskItemStatus": "NotStarted"
}

### Get all TaskItems for "max@mustermann.local"

GET {{RebacExperiments.Server.Api_HostAddress}}/TaskItems


### Sign In "philipp@bytefish.de"

POST {{RebacExperiments.Server.Api_HostAddress}}/SignInUser
Content-Type: application/json

{
  "username": "philipp@bytefish.de",
  "password": "5!F25GbKwU3P",
  "rememberMe": true
}

### Get all TaskItems for "philipp@bytefish.de"

GET {{RebacExperiments.Server.Api_HostAddress}}/TaskItems

